%% iscsi_protocol.pl
%%
%% A declarative model of the parts of the iSCSI protocol (RFC 3720) whose
%% behaviour is *logical* rather than wire-format: the login state machine,
%% login key negotiation result-functions, command-sequence-number windowing,
%% and CHAP message ordering.
%%
%% This model is the source of truth for a generated test corpus. Running
%% `?- emit_corpus.` (see Makefile target `corpus`) prints a line-oriented
%% corpus to stdout; the Rust integration test `tests/model_corpus_tests.rs`
%% replays that corpus against the real implementation and asserts the
%% implementation agrees with the model. Divergences mean either the model or
%% the implementation is wrong -- which is exactly what we want to surface.
%%
%% Tested with Scryer Prolog. Pure ISO + library(format)/lists/between.
%%
%% Scope note: this models the protocol *logic*, not PDU byte encoding, SCSI
%% block I/O, or socket/async behaviour. Those are serialization / I/O concerns
%% better covered by the crate's existing Rust tests.

:- use_module(library(format)).
:- use_module(library(lists)).
:- use_module(library(between)).

% forall/2 is not a Scryer builtin; define the standard meta-predicate.
forall(Cond, Action) :- \+ ( Cond, \+ Action ).

% ===========================================================================
% Entry point
% ===========================================================================

emit_corpus :-
    format("# iSCSI protocol model corpus~n", []),
    format("# GENERATED by model/iscsi_protocol.pl -- do not edit by hand.~n", []),
    format("# Regenerate with: make -C model corpus~n", []),
    format("#~n", []),
    format("# Columns are KIND key=value ...  (see model/README.md)~n", []),
    emit_seqwindow,
    emit_negotiate,
    emit_state,
    emit_chap.

% ===========================================================================
% Layer 1: Command-sequence-number window  (RFC 3720 Section 3.2.2.1)
%
% Models SessionData::validate_cmd_sn / sn_in_window in
% src/typestate_session.rs. The window [ExpCmdSN, MaxCmdSN] is compared using
% 32-bit serial-number arithmetic: a number is in-window iff the forward
% distance from ExpCmdSN is non-negative AND the forward distance to MaxCmdSN
% is non-negative, where "forward distance" is the signed interpretation of
% the 32-bit wrapping difference (the i32 cast in the Rust code).
% ===========================================================================

u32(X) :- X >= 0, X < 4294967296.

% signed32(+Unsigned32, -Signed): two's-complement reinterpretation.
signed32(U, S) :-
    ( U >= 2147483648 -> S is U - 4294967296 ; S = U ).

% wrap_sub(+A, +B, -D): (A - B) mod 2^32.
wrap_sub(A, B, D) :- D is (A - B) mod 4294967296.

% sn_in_window(+Sn, +Exp, +Max): mirrors the Rust sn_in_window helper.
sn_in_window(Sn, Exp, Max) :-
    wrap_sub(Sn, Exp, DiffExpU), signed32(DiffExpU, DiffExp),
    wrap_sub(Max, Sn, DiffMaxU), signed32(DiffMaxU, DiffMax),
    DiffExp >= 0, DiffMax >= 0.

window_expect(Sn, Exp, Max, accept) :- sn_in_window(Sn, Exp, Max), !.
window_expect(_, _, _, reject).

% Test points: small windows, boundary, and 32-bit wrap-around.
seqwindow_case(1,          1,          0).
seqwindow_case(1,          1,          1).
seqwindow_case(1,          1,          2).
seqwindow_case(1,          3,          0).
seqwindow_case(1,          3,          1).
seqwindow_case(1,          3,          2).
seqwindow_case(1,          3,          3).
seqwindow_case(1,          3,          4).
seqwindow_case(5,          5,          4).
seqwindow_case(5,          5,          5).
seqwindow_case(5,          5,          6).
seqwindow_case(10,         20,         9).
seqwindow_case(10,         20,         10).
seqwindow_case(10,         20,         15).
seqwindow_case(10,         20,         20).
seqwindow_case(10,         20,         21).
% Wrap-around window [0xFFFFFFFE, 0x00000001]
seqwindow_case(4294967294, 1,          4294967293).
seqwindow_case(4294967294, 1,          4294967294).
seqwindow_case(4294967294, 1,          4294967295).
seqwindow_case(4294967294, 1,          0).
seqwindow_case(4294967294, 1,          1).
seqwindow_case(4294967294, 1,          2).
% Degenerate window at zero
seqwindow_case(0,          0,          0).
seqwindow_case(0,          0,          1).
seqwindow_case(0,          0,          4294967295).

emit_seqwindow :-
    forall(seqwindow_case(Exp, Max, Sn),
           ( window_expect(Sn, Exp, Max, Expect),
             format("SEQWINDOW exp=~d max=~d sn=~d expect=~w~n",
                    [Exp, Max, Sn, Expect]) )).

% ===========================================================================
% Layer 2: Login key negotiation result-functions  (RFC 3720 Section 5.2/12)
%
% Models SessionData::apply_initiator_param. Each key has a target-side
% default and a "result function" that combines the initiator's offer with
% the target default. Numeric keys use Minimum or Maximum; booleans use the
% RFC AND/OR result functions; digests are forced to None (CRC32C disabled in
% this implementation); declarative per-connection keys are taken as-is.
% ===========================================================================

% neg_rule(Key, TargetDefault, ResultFunction)
neg_rule('MaxBurstLength',            262144, min).
neg_rule('FirstBurstLength',          65536,  min).
neg_rule('DefaultTime2Wait',          2,      max).
neg_rule('DefaultTime2Retain',        20,     min).
neg_rule('MaxOutstandingR2T',         1,      min).
neg_rule('ErrorRecoveryLevel',        0,      min).
neg_rule('MaxRecvDataSegmentLength',  0,      set).      % target stores offer as-is
neg_rule('ImmediateData',             yes,    and).      % default Yes
neg_rule('InitialR2T',                no,     or).       % default No
neg_rule('DataPDUInOrder',            yes,    set_bool).
neg_rule('DataSequenceInOrder',       yes,    set_bool).
neg_rule('HeaderDigest',              'None', force_none).
neg_rule('DataDigest',                'None', force_none).

% neg_result(+Function, +Default, +Offer, -Result)
neg_result(min,        D, O, R) :- ( O =< D -> R = O ; R = D ).
neg_result(max,        D, O, R) :- ( O >= D -> R = O ; R = D ).
neg_result(set,        _, O, O).
neg_result(set_bool,   _, O, O).
neg_result(and,        D, O, R) :- bool_and(D, O, R).
neg_result(or,         D, O, R) :- bool_or(D, O, R).
neg_result(force_none, _, _, 'None').

bool_and(yes, yes, yes) :- !.
bool_and(_,   _,   no).
bool_or(no, no, no) :- !.
bool_or(_,  _,  yes).

% Offers to exercise per key: below / equal / above default for numerics,
% both polarities for booleans, both algorithms for digests.
neg_offers('MaxBurstLength',           [131072, 262144, 524288]).
neg_offers('FirstBurstLength',         [32768, 65536, 131072]).
neg_offers('DefaultTime2Wait',         [0, 2, 5]).
neg_offers('DefaultTime2Retain',       [10, 20, 30]).
neg_offers('MaxOutstandingR2T',        [1, 8]).
neg_offers('ErrorRecoveryLevel',       [0, 2]).
neg_offers('MaxRecvDataSegmentLength', [4096, 16384]).
neg_offers('ImmediateData',            [yes, no]).
neg_offers('InitialR2T',               [yes, no]).
neg_offers('DataPDUInOrder',           [yes, no]).
neg_offers('DataSequenceInOrder',      [yes, no]).
neg_offers('HeaderDigest',             ['CRC32C', 'None']).
neg_offers('DataDigest',               ['CRC32C', 'None']).

emit_negotiate :-
    forall(( neg_rule(Key, Default, Fn), neg_offers(Key, Offers),
             member(Offer, Offers) ),
           ( neg_result(Fn, Default, Offer, Result),
             token(Offer,  OfferTok),
             token(Result, ResultTok),
             format("NEGOTIATE key=~w init=~w expect=~w~n",
                    [Key, OfferTok, ResultTok]) )).

% Render yes/no as the wire tokens Yes/No; pass everything else through.
token(yes, 'Yes') :- !.
token(no,  'No') :- !.
token(X,   X).

% ===========================================================================
% Layer 3: Login state machine  (RFC 3720 Section 5.3)
%
% Models a single process_login step from the initial Free state with
% AuthConfig::None and no AuthMethod offered (so security negotiation passes
% straight through). The resulting state is a function of the login PDU's
% CSG (current stage), NSG (next stage) and the Transit bit.
%
%   Stage encoding: 0 = SecurityNegotiation,
%                   1 = LoginOperationalNegotiation,
%                   3 = FullFeaturePhase.
% ===========================================================================

% next_state(+CSG, +NSG, +Transit, -StateName)
% CSG = 0: Free dispatches into SecurityNegotiation::continue_login.
next_state(0, NSG, 1, 'LoginOperationalNegotiation') :- NSG =:= 1, !.
next_state(0, NSG, 1, 'FullFeaturePhase')            :- NSG =:= 3, !.
next_state(0, _,   _, 'SecurityNegotiation')         :- !.
% CSG = 1: Free dispatches into LoginOperationalNegotiation::process_login.
next_state(1, NSG, 1, 'FullFeaturePhase')            :- NSG =:= 3, !.
next_state(1, _,   _, 'LoginOperationalNegotiation') :- !.
% CSG = 2 or 3: invalid initial CSG -> rejected.
next_state(_, _, _, 'Failed').

emit_state :-
    forall(( between(0, 3, CSG), between(0, 3, NSG), member(T, [0, 1]) ),
           ( next_state(CSG, NSG, T, State),
             format("STATE csg=~d nsg=~d transit=~d expect=~w~n",
                    [CSG, NSG, T, State]) )).

% ===========================================================================
% Layer 4: CHAP message ordering  (RFC 3720 Section 11 / RFC 1994)
%
% Models the legal ordering of the CHAP exchange when the target requires
% CHAP, and the coarse outcome of the first initiator message set. The full
% challenge/response (MD5 over identifier+secret+challenge) is not modelled --
% that is cryptographic detail covered by src/auth.rs unit tests -- but the
% *ordering* discipline is:
%
%   1. initiator offers AuthMethod=CHAP
%   2. target selects CHAP (AuthMethod=CHAP)
%   3. initiator sends CHAP_A (algorithm list)
%   4. target sends CHAP_I (identifier) + CHAP_C (challenge)
%   5. initiator sends CHAP_N (name) + CHAP_R (response)
%   6. target validates -> success
%
% Sending CHAP_N/CHAP_R before any CHAP_A (step 3), or refusing CHAP when the
% target requires it, is a protocol violation -> login rejected.
% ===========================================================================

% chap_case(Name, InitiatorParams, ExpectedState, ExpectedResponseKey)
% InitiatorParams: list of Key-Value (Value 'none' means key-only / dynamic).
% ExpectedResponseKey: Key-Value to assert present in the target response, or
% 'none' to assert nothing about the response body.
chap_case(offer_chap,
          ['AuthMethod'-'CHAP'],
          'SecurityNegotiation', 'AuthMethod'-'CHAP').
chap_case(send_chap_a,
          ['CHAP_A'-'5'],
          'SecurityNegotiation', 'CHAP_C'-none).
chap_case(out_of_order,
          ['CHAP_N'-user, 'CHAP_R'-'0xab'],
          'Failed', none).
chap_case(refuse_chap,
          ['AuthMethod'-'None'],
          'Failed', none).

emit_chap :-
    forall(chap_case(Name, Params, State, Key),
           ( params_field(Params, ParamsField),
             key_field(Key, KeyField),
             format("CHAP case=~w params=~w expect_state=~w expect_key=~w~n",
                    [Name, ParamsField, State, KeyField]) )).

% Encode [K1-V1, K2-V2] as "K1:V1,K2:V2".
params_field([], '-').
params_field([K-V|Rest], Field) :-
    pair_tok(K, V, First),
    params_field_rest(Rest, First, Field).

params_field_rest([], Acc, Acc).
params_field_rest([K-V|Rest], Acc, Field) :-
    pair_tok(K, V, P),
    atomic_list_concat([Acc, ',', P], Acc1),
    params_field_rest(Rest, Acc1, Field).

pair_tok(K, V, Tok) :- atomic_list_concat([K, ':', V], Tok).

key_field(none, none) :- !.
key_field(K-none, K) :- !.
key_field(K-V, Field) :- atomic_list_concat([K, '=', V], Field).

% atomic_list_concat/2 shim (Scryer provides it via library(lists)? define if not).
atomic_list_concat(List, Atom) :-
    phrase(concat_atoms(List), Codes),
    atom_codes(Atom, Codes).

concat_atoms([]) --> [].
concat_atoms([A|As]) -->
    { atom_codes(A, Cs) }, string_codes(Cs), concat_atoms(As).

string_codes([]) --> [].
string_codes([C|Cs]) --> [C], string_codes(Cs).
