%% iscsi_protocol.pl
%%
%% An executable model of the *logical* layers of the iSCSI protocol, derived
%% from RFC 3720 (and RFC 1994 for CHAP, RFC 1982 for serial-number
%% arithmetic) -- NOT from the Rust implementation. The rules below encode
%% what the RFC says; the Rust integration test then checks the implementation
%% against this independent oracle.
%%
%% Why derive from the RFC and not the code: the implementation (and its own
%% unit tests) can share the same misreading of the spec. A model that merely
%% restates the code is a tautology. So each negotiation rule cites its RFC
%% section, and every place the implementation deliberately or accidentally
%% diverges is recorded in an explicit deviation/5 registry rather than baked
%% in silently.
%%
%% RFC 3720 Section 12 result functions used here (verified against the spec
%% and the UNH-IOL iSCSI test suite):
%%   HeaderDigest/DataDigest 12.1  : list selection (None | CRC32C), default None
%%   InitialR2T              12.10 : boolean OR,  default Yes
%%   ImmediateData           12.11 : boolean AND, default Yes
%%   MaxRecvDataSegmentLength 12.12: declarative, default 8192
%%   MaxBurstLength          12.13 : Minimum, default 262144
%%   FirstBurstLength        12.14 : Minimum, default 65536; MUST NOT exceed MaxBurstLength
%%   DefaultTime2Wait        12.15 : Maximum, default 2
%%   DefaultTime2Retain      12.16 : Minimum, default 20
%%   MaxOutstandingR2T       12.17 : Minimum, default 1
%%   DataPDUInOrder          12.18 : boolean OR,  default Yes
%%   DataSequenceInOrder     12.19 : boolean OR,  default Yes
%%   ErrorRecoveryLevel      12.20 : Minimum, default 0
%%
%% Tested with Scryer Prolog. Regenerate the corpus with: make -C model corpus

:- use_module(library(format)).
:- use_module(library(lists)).
:- use_module(library(between)).

% forall/2 is not a Scryer builtin; define the standard meta-predicate.
forall(Cond, Action) :- \+ ( Cond, \+ Action ).

% ===========================================================================
% Entry point
% ===========================================================================

emit_corpus :-
    format("# iSCSI protocol model corpus~n", []),
    format("# GENERATED by model/iscsi_protocol.pl -- do not edit by hand.~n", []),
    format("# Derived from RFC 3720 / RFC 1994 / RFC 1982, NOT from the Rust code.~n", []),
    format("# Regenerate with: make -C model corpus~n", []),
    format("#~n", []),
    emit_deviation_legend,
    format("#~n", []),
    emit_seqwindow,
    emit_negotiate,
    emit_constraint,
    emit_default,
    emit_state,
    emit_chap.

% ===========================================================================
% Deviation registry
%
% deviation(Id, Subject, RfcSays, ImplDoes, RfcRef). Each is a place where the
% implementation diverges from the RFC. The corpus tags affected rows with
% `status=deviation:Id`; the Rust test asserts the divergence is real (impl
% != rfc) AND that the full set of Ids seen matches this registry, so a fixed
% deviation or a new one both force the registry to be updated.
% ===========================================================================

deviation('D1', 'HeaderDigest/DataDigest',
          'negotiable list {None,CRC32C}, may select CRC32C',
          'forced to None unconditionally (digest I/O path not plumbed)',
          'RFC 3720 12.1; src/typestate_session.rs:296-302').
deviation('D4', 'InitialR2T default',
          'default value is Yes',
          'default value is No (deliberate immediate-data optimisation)',
          'RFC 3720 12.10; src/session.rs:119').

% Fixed deviations (kept for the record; no longer present in the code):
%   D2  FirstBurstLength <= MaxBurstLength now enforced (RFC 3720 12.14).
%   D3  DataPDUInOrder/DataSequenceInOrder now use the OR result function
%       (RFC 3720 12.18-12.19).

emit_deviation_legend :-
    format("# Known deviations from RFC 3720 (audited, see deviation/5):~n", []),
    forall(deviation(Id, Subject, Rfc, Impl, Ref),
           format("#   ~w  ~w: RFC says \"~w\"; impl \"~w\"  [~w]~n",
                  [Id, Subject, Rfc, Impl, Ref])).

% ===========================================================================
% Layer 1: Command-sequence-number window  (RFC 3720 3.2.2.1; RFC 1982)
%
% A CmdSN is in-window iff the signed 32-bit forward distance from ExpCmdSN is
% >= 0 and the signed forward distance to MaxCmdSN is >= 0. This is pure
% serial-number arithmetic from the RFC; it does not reference the code.
% ===========================================================================

signed32(U, S) :- ( U >= 2147483648 -> S is U - 4294967296 ; S = U ).
wrap_sub(A, B, D) :- D is (A - B) mod 4294967296.

sn_in_window(Sn, Exp, Max) :-
    wrap_sub(Sn, Exp, DiffExpU), signed32(DiffExpU, DiffExp),
    wrap_sub(Max, Sn, DiffMaxU), signed32(DiffMaxU, DiffMax),
    DiffExp >= 0, DiffMax >= 0.

window_expect(Sn, Exp, Max, accept) :- sn_in_window(Sn, Exp, Max), !.
window_expect(_, _, _, reject).

seqwindow_case(1,          1,          0).
seqwindow_case(1,          1,          1).
seqwindow_case(1,          1,          2).
seqwindow_case(1,          3,          0).
seqwindow_case(1,          3,          1).
seqwindow_case(1,          3,          2).
seqwindow_case(1,          3,          3).
seqwindow_case(1,          3,          4).
seqwindow_case(5,          5,          4).
seqwindow_case(5,          5,          5).
seqwindow_case(5,          5,          6).
seqwindow_case(10,         20,         9).
seqwindow_case(10,         20,         10).
seqwindow_case(10,         20,         15).
seqwindow_case(10,         20,         20).
seqwindow_case(10,         20,         21).
seqwindow_case(4294967294, 1,          4294967293).
seqwindow_case(4294967294, 1,          4294967294).
seqwindow_case(4294967294, 1,          4294967295).
seqwindow_case(4294967294, 1,          0).
seqwindow_case(4294967294, 1,          1).
seqwindow_case(4294967294, 1,          2).
seqwindow_case(0,          0,          0).
seqwindow_case(0,          0,          1).
seqwindow_case(0,          0,          4294967295).

emit_seqwindow :-
    forall(seqwindow_case(Exp, Max, Sn),
           ( window_expect(Sn, Exp, Max, Expect),
             format("SEQWINDOW exp=~w max=~w sn=~w expect=~w~n",
                    [Exp, Max, Sn, Expect]) )).

% ===========================================================================
% Layer 2: Login key negotiation result-functions  (RFC 3720 Section 12)
%
% For each case we compute the RFC-correct result of combining the target's
% current value with the initiator's offer, AND what the implementation
% actually produces, then mark the row conform or deviation. The Rust test
% sets the target value explicitly so the *result function* itself is tested,
% not just behaviour at the default.
% ===========================================================================

rfc_section('HeaderDigest',             '12.1').
rfc_section('DataDigest',               '12.1').
rfc_section('InitialR2T',               '12.10').
rfc_section('ImmediateData',            '12.11').
rfc_section('MaxRecvDataSegmentLength', '12.12').
rfc_section('MaxBurstLength',           '12.13').
rfc_section('FirstBurstLength',         '12.14').
rfc_section('DefaultTime2Wait',         '12.15').
rfc_section('DefaultTime2Retain',       '12.16').
rfc_section('MaxOutstandingR2T',        '12.17').
rfc_section('DataPDUInOrder',           '12.18').
rfc_section('DataSequenceInOrder',      '12.19').
rfc_section('ErrorRecoveryLevel',       '12.20').

% rfc_combine(+Key, +Target, +Offer, -Result): what the RFC mandates.
rfc_combine('MaxBurstLength',           T, O, R) :- imin(T, O, R).
rfc_combine('FirstBurstLength',         T, O, R) :- imin(T, O, R).
rfc_combine('DefaultTime2Wait',         T, O, R) :- imax(T, O, R).
rfc_combine('DefaultTime2Retain',       T, O, R) :- imin(T, O, R).
rfc_combine('MaxOutstandingR2T',        T, O, R) :- imin(T, O, R).
rfc_combine('ErrorRecoveryLevel',       T, O, R) :- imin(T, O, R).
rfc_combine('MaxRecvDataSegmentLength', _, O, O).          % declarative
rfc_combine('ImmediateData',            T, O, R) :- band(T, O, R).
rfc_combine('InitialR2T',               T, O, R) :- bor(T, O, R).
rfc_combine('DataPDUInOrder',           T, O, R) :- bor(T, O, R).
rfc_combine('DataSequenceInOrder',      T, O, R) :- bor(T, O, R).
rfc_combine('HeaderDigest',             _, O, O).          % target supports {None,CRC32C}
rfc_combine('DataDigest',               _, O, O).

% impl_combine(+Key, +Target, +Offer, -Result): what src/typestate_session.rs
% actually does (apply_initiator_param), modelled faithfully.
impl_combine('MaxBurstLength',           T, O, R) :- imin(T, O, R).
impl_combine('FirstBurstLength',         T, O, R) :- imin(T, O, R).
impl_combine('DefaultTime2Wait',         T, O, R) :- imax(T, O, R).
impl_combine('DefaultTime2Retain',       T, O, R) :- imin(T, O, R).
impl_combine('MaxOutstandingR2T',        T, O, R) :- imin(T, O, R).
impl_combine('ErrorRecoveryLevel',       T, O, R) :- imin(T, O, R).
impl_combine('MaxRecvDataSegmentLength', _, O, O).
impl_combine('ImmediateData',            T, O, R) :- band(T, O, R).
impl_combine('InitialR2T',               T, O, R) :- bor(T, O, R).
impl_combine('DataPDUInOrder',           T, O, R) :- bor(T, O, R).   % fixed: OR
impl_combine('DataSequenceInOrder',      T, O, R) :- bor(T, O, R).   % fixed: OR
impl_combine('HeaderDigest',             _, _, 'None').    % D1: forced None
impl_combine('DataDigest',               _, _, 'None').    % D1: forced None

imin(A, B, A) :- A =< B, !.
imin(_, B, B).
imax(A, B, A) :- A >= B, !.
imax(_, B, B).
band(yes, yes, yes) :- !.
band(_,   _,   no).
bor(no, no, no) :- !.
bor(_,  _,  yes).

% Which deviation a Key/result mismatch belongs to.
dev_id('HeaderDigest',        'D1').
dev_id('DataDigest',          'D1').

% neg_case(Key, TargetValue, InitiatorOffer)
% Numerics: target = RFC default, offers below/equal/above.
neg_case('MaxBurstLength',           262144, 131072).
neg_case('MaxBurstLength',           262144, 262144).
neg_case('MaxBurstLength',           262144, 524288).
neg_case('FirstBurstLength',         65536,  32768).
neg_case('FirstBurstLength',         65536,  131072).
neg_case('DefaultTime2Wait',         2,      0).
neg_case('DefaultTime2Wait',         2,      5).
neg_case('DefaultTime2Retain',       20,     10).
neg_case('DefaultTime2Retain',       20,     30).
neg_case('MaxOutstandingR2T',        1,      8).
neg_case('ErrorRecoveryLevel',       0,      2).
neg_case('MaxRecvDataSegmentLength', 8192,   4096).
neg_case('MaxRecvDataSegmentLength', 8192,   16384).
% Booleans: full 2x2 target x offer to exercise the result function.
neg_case('InitialR2T',               yes, yes).
neg_case('InitialR2T',               yes, no).
neg_case('InitialR2T',               no,  yes).
neg_case('InitialR2T',               no,  no).
neg_case('ImmediateData',            yes, yes).
neg_case('ImmediateData',            yes, no).
neg_case('ImmediateData',            no,  yes).
neg_case('ImmediateData',            no,  no).
neg_case('DataPDUInOrder',           yes, yes).
neg_case('DataPDUInOrder',           yes, no).
neg_case('DataPDUInOrder',           no,  yes).
neg_case('DataPDUInOrder',           no,  no).
neg_case('DataSequenceInOrder',      yes, yes).
neg_case('DataSequenceInOrder',      yes, no).
neg_case('DataSequenceInOrder',      no,  yes).
neg_case('DataSequenceInOrder',      no,  no).
% Digests: target advertises CRC32C support; offers CRC32C / None.
neg_case('HeaderDigest',             'CRC32C', 'CRC32C').
neg_case('HeaderDigest',             'CRC32C', 'None').
neg_case('DataDigest',               'CRC32C', 'CRC32C').
neg_case('DataDigest',               'CRC32C', 'None').

emit_negotiate :-
    forall(neg_case(Key, Target, Offer),
           ( rfc_combine(Key, Target, Offer, RfcR),
             impl_combine(Key, Target, Offer, ImplR),
             rfc_section(Key, Sec),
             neg_status(Key, RfcR, ImplR, Status),
             token(Target, TTok), token(Offer, OTok),
             token(RfcR, RTok), token(ImplR, XTok),
             format("NEGOTIATE key=~w target=~w init=~w rfc=~w impl=~w section=~w status=~w~n",
                    [Key, TTok, OTok, RTok, XTok, Sec, Status]) )).

neg_status(_, R, R, conform) :- !.
neg_status(Key, _, _, Status) :- dev_id(Key, Id), dev_status(Id, Status).
dev_status(Id, Status) :- atomic_list_concat([deviation, ':', Id], Status).

token(yes, 'Yes') :- !.
token(no,  'No') :- !.
token(X,   X).

% ===========================================================================
% Layer 2b: Cross-key constraint  (RFC 3720 12.14)
%
% "FirstBurstLength MUST NOT exceed MaxBurstLength." The implementation now
% enforces this (formerly deviation D2). The expected values are computed from
% the per-key Minimum plus the clamp, and the result must satisfy the
% constraint (first =< max).
% ===========================================================================

% constraint_case(Name, MaxBurstOffer, FirstBurstOffer): defaults 262144/65536.
constraint_case(first_burst_le_max_burst, 1024, 65536).

emit_constraint :-
    forall(constraint_case(Name, MBO, FBO),
           ( imin(262144, MBO, EMax),
             imin(65536, FBO, F1), imin(F1, EMax, EFirst),
             ( EFirst =< EMax -> Rfc = valid ; Rfc = invalid ),
             ( Rfc == valid -> Status = conform ; dev_status('D2', Status) ),
             format("CONSTRAINT name=~w max_burst_offer=~w first_burst_offer=~w expect_max=~w expect_first=~w rfc=~w status=~w~n",
                    [Name, MBO, FBO, EMax, EFirst, Rfc, Status]) )).

% ===========================================================================
% Layer 2c: Default-value conformance  (RFC 3720 Section 12)
%
% The assumed-if-absent default of each key. Most match; InitialR2T does not
% (RFC Yes vs impl No) -> deviation D4.
% ===========================================================================

% default_case(Key, ImplDefault, RfcDefault, Section)
default_case('InitialR2T',      no,     yes,    '12.10').
default_case('ImmediateData',   yes,    yes,    '12.11').
default_case('MaxBurstLength',  262144, 262144, '12.13').
default_case('FirstBurstLength',65536,  65536,  '12.14').
default_case('DataPDUInOrder',  yes,    yes,    '12.18').
default_case('ErrorRecoveryLevel', 0,   0,      '12.20').

emit_default :-
    forall(default_case(Key, ImplD, RfcD, Sec),
           ( ( ImplD == RfcD -> Status = conform ; dev_status('D4', Status) ),
             token(ImplD, ITok), token(RfcD, RTok),
             format("DEFAULT key=~w impl_default=~w rfc_default=~w section=~w status=~w~n",
                    [Key, ITok, RTok, Sec, Status]) )).

% ===========================================================================
% Layer 3: Login state machine  (RFC 3720 Section 5.3)
%
% A single login step from Free with AuthMethod=None negotiated through. The
% resulting phase is a function of the PDU's CSG/NSG/Transit per the RFC stage
% codes (0=SecurityNegotiation, 1=LoginOperationalNegotiation,
% 3=FullFeaturePhase). Illegal initial CSG (2,3) => login fails.
% ===========================================================================

next_state(0, NSG, 1, 'LoginOperationalNegotiation') :- NSG =:= 1, !.
next_state(0, NSG, 1, 'FullFeaturePhase')            :- NSG =:= 3, !.
next_state(0, _,   _, 'SecurityNegotiation')         :- !.
next_state(1, NSG, 1, 'FullFeaturePhase')            :- NSG =:= 3, !.
next_state(1, _,   _, 'LoginOperationalNegotiation') :- !.
next_state(_, _, _, 'Failed').

emit_state :-
    forall(( between(0, 3, CSG), between(0, 3, NSG), member(T, [0, 1]) ),
           ( next_state(CSG, NSG, T, State),
             format("STATE csg=~w nsg=~w transit=~w expect=~w~n",
                    [CSG, NSG, T, State]) )).

% ===========================================================================
% Layer 4: CHAP message ordering  (RFC 3720 Section 11; RFC 1994)
%
% Legal ordering: AuthMethod=CHAP -> CHAP_A -> {CHAP_I,CHAP_C} ->
% {CHAP_N,CHAP_R} -> success. Sending CHAP_N/CHAP_R before any CHAP_A, or
% refusing CHAP when the target requires it, is a violation -> login fails.
% ===========================================================================

chap_case(offer_chap,
          ['AuthMethod'-'CHAP'],
          'SecurityNegotiation', 'AuthMethod'-'CHAP').
chap_case(send_chap_a,
          ['CHAP_A'-'5'],
          'SecurityNegotiation', 'CHAP_C'-none).
chap_case(out_of_order,
          ['CHAP_N'-user, 'CHAP_R'-'0xab'],
          'Failed', none).
chap_case(refuse_chap,
          ['AuthMethod'-'None'],
          'Failed', none).

emit_chap :-
    forall(chap_case(Name, Params, State, Key),
           ( params_field(Params, ParamsField),
             key_field(Key, KeyField),
             format("CHAP case=~w params=~w expect_state=~w expect_key=~w~n",
                    [Name, ParamsField, State, KeyField]) )).

params_field([], '-').
params_field([K-V|Rest], Field) :-
    pair_tok(K, V, First),
    params_field_rest(Rest, First, Field).
params_field_rest([], Acc, Acc).
params_field_rest([K-V|Rest], Acc, Field) :-
    pair_tok(K, V, P),
    atomic_list_concat([Acc, ',', P], Acc1),
    params_field_rest(Rest, Acc1, Field).
pair_tok(K, V, Tok) :- atomic_list_concat([K, ':', V], Tok).

key_field(none, none) :- !.
key_field(K-none, K) :- !.
key_field(K-V, Field) :- atomic_list_concat([K, '=', V], Field).

% ===========================================================================
% atomic_list_concat/2 (Scryer has no builtin): concatenate atoms.
% ===========================================================================

atomic_list_concat(List, Atom) :-
    phrase(concat_atoms(List), Codes),
    atom_codes(Atom, Codes).

concat_atoms([]) --> [].
concat_atoms([A|As]) -->
    { ( atom(A) -> atom_codes(A, Cs) ; number_codes(A, Cs) ) },
    seq_codes(Cs), concat_atoms(As).

seq_codes([]) --> [].
seq_codes([C|Cs]) --> [C], seq_codes(Cs).
