//! Model-based conformance tests driven by the Scryer Prolog protocol model.
//!
//! The corpus at `tests/corpus/iscsi_model_corpus.txt` is generated by
//! `model/iscsi_protocol.pl` (see `model/README.md`). Each row encodes a case
//! and the *model's* predicted outcome. These tests replay every row against
//! the real implementation and assert the implementation agrees with the
//! model. A mismatch means the model and the code disagree about RFC 3720 --
//! either a modelling bug or an implementation bug, both worth knowing.
//!
//! Layers covered:
//!   SEQWINDOW  - command sequence number windowing (validate_cmd_sn)
//!   NEGOTIATE  - login key result-functions (apply_initiator_param)
//!   STATE      - login state machine transitions (AnySession::process_login)
//!   CHAP       - CHAP message ordering / coarse outcomes

use std::collections::HashMap;
use std::path::PathBuf;

use iscsi_target::pdu::{self, IscsiPdu};
use iscsi_target::session::DigestType;
use iscsi_target::typestate_session::{AnySession, SessionData};
use iscsi_target::{AuthConfig, ChapCredentials};

const TARGET_NAME: &str = "iqn.2025-12.local:test.target";
const INITIATOR_NAME: &str = "iqn.2025-12.local:test.initiator";

// ---------------------------------------------------------------------------
// Corpus loading / parsing
// ---------------------------------------------------------------------------

struct Row {
    kind: String,
    fields: HashMap<String, String>,
}

fn load_corpus() -> Vec<Row> {
    let path: PathBuf = [env!("CARGO_MANIFEST_DIR"), "tests", "corpus", "iscsi_model_corpus.txt"]
        .iter()
        .collect();
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read corpus {}: {}", path.display(), e));

    let mut rows = Vec::new();
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let mut parts = line.split_whitespace();
        let kind = parts.next().expect("row has a kind").to_string();
        let mut fields = HashMap::new();
        for tok in parts {
            if let Some((k, v)) = tok.split_once('=') {
                fields.insert(k.to_string(), v.to_string());
            }
        }
        rows.push(Row { kind, fields });
    }
    assert!(!rows.is_empty(), "corpus is empty");
    rows
}

fn rows_of(kind: &str) -> Vec<Row> {
    load_corpus().into_iter().filter(|r| r.kind == kind).collect()
}

fn field<'a>(r: &'a Row, key: &str) -> &'a str {
    r.fields
        .get(key)
        .unwrap_or_else(|| panic!("{} row missing field '{}'", r.kind, key))
}

// ---------------------------------------------------------------------------
// PDU construction helper
// ---------------------------------------------------------------------------

fn login_pdu(csg: u8, nsg: u8, transit: bool, params: &[(&str, &str)]) -> IscsiPdu {
    let owned: Vec<(String, String)> = params
        .iter()
        .map(|(k, v)| (k.to_string(), v.to_string()))
        .collect();
    let data = pdu::serialize_text_parameters(&owned);
    IscsiPdu::login_request(
        [0x01, 0x02, 0x03, 0x04, 0x05, 0x06],
        0, // TSIH
        0, // CID
        0, // CmdSN
        0, // ExpStatSN
        csg,
        nsg,
        transit,
        data,
    )
}

// ---------------------------------------------------------------------------
// Layer 1: command sequence number window
// ---------------------------------------------------------------------------

#[test]
fn model_seqwindow_matches_implementation() {
    let mut checked = 0;
    for r in rows_of("SEQWINDOW") {
        let exp: u32 = field(&r, "exp").parse().unwrap();
        let max: u32 = field(&r, "max").parse().unwrap();
        let sn: u32 = field(&r, "sn").parse().unwrap();
        let expect_accept = field(&r, "expect") == "accept";

        let mut data = SessionData::default();
        data.exp_cmd_sn = exp;
        data.max_cmd_sn = max;
        let in_window = data.validate_cmd_sn(sn);

        assert_eq!(
            in_window, expect_accept,
            "SEQWINDOW exp={} max={} sn={}: model said {}, impl said {}",
            exp, max, sn, expect_accept, in_window
        );
        checked += 1;
    }
    assert!(checked > 0, "no SEQWINDOW rows exercised");
}

// ---------------------------------------------------------------------------
// Layer 2: login key negotiation result-functions
// ---------------------------------------------------------------------------

/// Read back the negotiated value for `key` as a wire-comparable string.
fn negotiated_value(data: &SessionData, key: &str) -> String {
    match key {
        "MaxBurstLength" => data.params.max_burst_length.to_string(),
        "FirstBurstLength" => data.params.first_burst_length.to_string(),
        "DefaultTime2Wait" => data.params.default_time2wait.to_string(),
        "DefaultTime2Retain" => data.params.default_time2retain.to_string(),
        "MaxOutstandingR2T" => data.params.max_outstanding_r2t.to_string(),
        "ErrorRecoveryLevel" => data.params.error_recovery_level.to_string(),
        "MaxRecvDataSegmentLength" => data.params.max_xmit_data_segment_length.to_string(),
        "ImmediateData" => yes_no(data.params.immediate_data),
        "InitialR2T" => yes_no(data.params.initial_r2t),
        "DataPDUInOrder" => yes_no(data.params.data_pdu_in_order),
        "DataSequenceInOrder" => yes_no(data.params.data_sequence_in_order),
        "HeaderDigest" => digest_str(data.params.header_digest),
        "DataDigest" => digest_str(data.params.data_digest),
        other => panic!("unknown negotiation key in corpus: {}", other),
    }
}

fn yes_no(b: bool) -> String {
    if b { "Yes" } else { "No" }.to_string()
}

fn digest_str(d: DigestType) -> String {
    match d {
        DigestType::None => "None",
        DigestType::CRC32C => "CRC32C",
    }
    .to_string()
}

#[test]
fn model_negotiate_matches_implementation() {
    let mut checked = 0;
    for r in rows_of("NEGOTIATE") {
        let key = field(&r, "key");
        let init = field(&r, "init");
        let expect = field(&r, "expect");

        let mut data = SessionData::default();
        data.apply_initiator_param(key, init);
        let actual = negotiated_value(&data, key);

        assert_eq!(
            actual, expect,
            "NEGOTIATE {}={}: model said {}, impl produced {}",
            key, init, expect, actual
        );
        checked += 1;
    }
    assert!(checked > 0, "no NEGOTIATE rows exercised");
}

// ---------------------------------------------------------------------------
// Layer 3: login state machine
// ---------------------------------------------------------------------------

#[test]
fn model_state_machine_matches_implementation() {
    let mut checked = 0;
    for r in rows_of("STATE") {
        let csg: u8 = field(&r, "csg").parse().unwrap();
        let nsg: u8 = field(&r, "nsg").parse().unwrap();
        let transit = field(&r, "transit") == "1";
        let expect = field(&r, "expect");

        let pdu = login_pdu(csg, nsg, transit, &[("InitiatorName", INITIATOR_NAME)]);
        let session = AnySession::new();
        let (next, _responses) = session
            .process_login(&pdu, TARGET_NAME)
            .expect("process_login should not hard-error");

        assert_eq!(
            next.state_name(),
            expect,
            "STATE csg={} nsg={} transit={}: model said {}, impl reached {}",
            csg,
            nsg,
            transit,
            expect,
            next.state_name()
        );
        checked += 1;
    }
    assert!(checked > 0, "no STATE rows exercised");
}

// ---------------------------------------------------------------------------
// Layer 4: CHAP message ordering
// ---------------------------------------------------------------------------

/// Parse the corpus "params" field ("K1:V1,K2:V2" or "-") into pairs.
fn parse_chap_params(field: &str) -> Vec<(String, String)> {
    if field == "-" {
        return Vec::new();
    }
    field
        .split(',')
        .filter_map(|pair| pair.split_once(':'))
        .map(|(k, v)| (k.to_string(), v.to_string()))
        .collect()
}

#[test]
fn model_chap_ordering_matches_implementation() {
    let mut checked = 0;
    for r in rows_of("CHAP") {
        let expect_state = field(&r, "expect_state");
        let expect_key = field(&r, "expect_key");
        let chap_params = parse_chap_params(field(&r, "params"));

        // Target requires one-way CHAP.
        let auth = AuthConfig::Chap {
            credentials: ChapCredentials::new("user", "secret"),
        };
        let session = AnySession::new_configured(auth, TARGET_NAME, "", None);

        // Initiator always supplies InitiatorName, then the case's params,
        // entering the security negotiation phase (csg=0).
        let mut params: Vec<(&str, &str)> = vec![("InitiatorName", INITIATOR_NAME)];
        for (k, v) in &chap_params {
            params.push((k.as_str(), v.as_str()));
        }
        let pdu = login_pdu(0, 0, false, &params);

        let (next, responses) = session
            .process_login(&pdu, TARGET_NAME)
            .expect("process_login should not hard-error");

        assert_eq!(
            next.state_name(),
            expect_state,
            "CHAP case '{}': model said state {}, impl reached {}",
            field(&r, "case"),
            expect_state,
            next.state_name()
        );

        if expect_key != "none" {
            let resp_params: Vec<(String, String)> = responses
                .iter()
                .flat_map(|p| pdu::parse_text_parameters(&p.data).unwrap_or_default())
                .collect();

            match expect_key.split_once('=') {
                Some((k, v)) => assert!(
                    resp_params.iter().any(|(rk, rv)| rk == k && rv == v),
                    "CHAP case '{}': expected response key {}={}, got {:?}",
                    field(&r, "case"),
                    k,
                    v,
                    resp_params
                ),
                None => assert!(
                    resp_params.iter().any(|(rk, _)| rk == expect_key),
                    "CHAP case '{}': expected response to contain key {}, got {:?}",
                    field(&r, "case"),
                    expect_key,
                    resp_params
                ),
            }
        }
        checked += 1;
    }
    assert!(checked > 0, "no CHAP rows exercised");
}
